version: '3'

services:
  maribo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    depends_on:
      - maribo_db

  maribo_db:
    image: postgres:13
    env_file: ../.env
    restart: always
